package com.tourney.exception;

public enum TournamentErrorCode {
    TOURNAMENT_NOT_FOUND,
    INVALID_ROUND_STATE,
    INVALID_TOURNAMENT_STATE,
    INVALID_MATCH_STATE,
    SCORE_SUBMISSION_CLOSED,
    UNAUTHORIZED_OPERATION,
    ROUND_NOT_FOUND
}

